Wallet with currency conversion
233blr/ReactWallet pull request #1
Opened 2022-01-04 13:23 UTC by 233blr

react-native;
Authentication and data storage - firebase;
For cyrrency conversion - https://exchangerate.host/#/#docs

Not implemented:
context api - there's no point,
firebase notification - to create an app, had to use https://rnfirebase.io/

2022-01-05 10:25 UTC, wizrdr requested changes

2022-01-05 10:25 UTC, wizrdr commented on screens/LoginScreen.js
> +				console.log('Registered with:', user.email);
remove

2022-01-05 10:25 UTC, wizrdr commented on screens/LoginScreen.js
> +				console.log('Logged in with:', user.email);
same

2022-01-05 10:25 UTC, wizrdr commented on screens/LoginScreen.js
> +					onChangeText={text => setEmail(text)}
вынеси в отдельную функцию

2022-01-05 10:25 UTC, wizrdr commented on screens/LoginScreen.js
> +					onChangeText={text => setPassword(text)}
вынеси в отдельную функцию

2022-01-05 10:25 UTC, wizrdr commented on components/HistoryButtons.js
> +				}
вынеси в отдельную функцию

2022-01-05 10:25 UTC, wizrdr commented on components/HistoryButtons.js
> +				}
вынеси в отделньую функцию

2022-01-05 10:25 UTC, wizrdr commented on components/TransactionHistItem.js
> +			<Text>date: {new Date(data.date).toUTCString().slice(5, 22)}</Text>
Лучше из этого сделать утил функцию

2022-01-05 10:25 UTC, wizrdr commented on components/TransactionInputItem.js
> +			onPress={() => onPress(item)}
отдельная функция

2022-01-05 10:25 UTC, wizrdr commented on components/TransactionInputList.js
> +				keyExtractor={(item, index) => index.toString()}
отдельная фунцкия

2022-01-05 10:25 UTC, wizrdr commented on navigator/tabs.js
> +							}}
вынеси в отдельную функцию

2022-01-05 10:25 UTC, wizrdr commented on navigator/tabs.js
> +							}}
тоже самое

2022-01-05 10:25 UTC, wizrdr commented on navigator/tabs.js
> +							}}
тоже самое

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +// import { URL } from '../api/exchangerate';
удали

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +				.catch(error => alert(error.message))
Создай отдельную апи для все запросов через axios

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +					onRequestClose={() => setModalVisible(!modalVisible)}
вынеси в отдельную функцию

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +							.map(item => (
не обязательно для этого делать 2 прохода

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +									}}
отдельная функция

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +							onPressButton={() => setModalVisible(!modalVisible)}
отдельная функция

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +						onChangeValue={text => setAmountFrom(text)}
отдельные функция

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +						}}
отдельная функция

2022-01-05 10:25 UTC, wizrdr commented on screens/CurrencyConverter.js
> +						onPressButton={() => setCurrencyValue([...currencyValue.reverse()])}
отдельная функция

2022-01-05 13:24 UTC, 233blr commented on screens/LoginScreen.js
> +				console.log('Registered with:', user.email);
Fixed in new version
(https://github.com/233blr/ReactWallet/blob/develop/screens/Login.js)

2022-01-05 13:24 UTC, 233blr commented on screens/LoginScreen.js
> +				console.log('Logged in with:', user.email);
Fixed in new version
(https://github.com/233blr/ReactWallet/blob/develop/screens/Login.js)

2022-01-05 14:27 UTC, 233blr commented on screens/LoginScreen.js
> +					onChangeText={text => setEmail(text)}
fixed

2022-01-05 14:27 UTC, 233blr commented on screens/LoginScreen.js
> +					onChangeText={text => setPassword(text)}
fixed

2022-01-05 14:32 UTC, 233blr commented on components/HistoryButtons.js
> +				}
fixed

2022-01-05 14:34 UTC, 233gme commented on screens/CurrencyConverter.js
> +									}}
fixed

2022-01-05 14:46 UTC, 233gme commented on screens/CurrencyConverter.js
> +							onPressButton={() => setModalVisible(!modalVisible)}
fixed

2022-01-05 14:49 UTC, 233blr commented on screens/CurrencyConverter.js
> +						onChangeValue={text => setAmountFrom(text)}
fixed

2022-01-05 14:54 UTC, 233blr commented on screens/CurrencyConverter.js
> +						onPressButton={() => setCurrencyValue([...currencyValue.reverse()])}
fixed

2022-01-05 14:54 UTC, 233gme commented on screens/CurrencyConverter.js
> +						}}
fixed

2022-01-06 10:54 UTC, wizrdr commented on screens/CurrencyConverter.js
> +						onChangeValue={text => getConversionSum(text)}
не вешай анонимные стрелочные функции как обработчик

2022-01-10 13:38 UTC, wizrdr commented on components/HistoryButtons.js
> +	const {flag, setFlag} = useContext(TransactionsContext);
Сделай более осмысленное название

2022-01-10 13:40 UTC, wizrdr commented on context/CurrencyContext.js
> +	const closeModal = () => setModalVisible(!modalVisible);
лучше назвать toggleModal

2022-01-10 13:41 UTC, wizrdr commented on context/CurrencyContext.js
> +		setModalVisible(!modalVisible);
можно использовать функцию коотрая написана ниже

2022-01-10 13:42 UTC, wizrdr commented on context/CurrencyContext.js
> +	const closeModal = () => setModalVisible(!modalVisible);
или поменять на setModalVisible(false)

2022-01-10 13:43 UTC, wizrdr commented on context/TransactionsContext.js
> +	};
по сути это 2 одинаковые функции с различием в 1 строке, лучше не дублировать код

2022-01-10 13:43 UTC, wizrdr commented on context/TransactionsContext.js
> +	};
вынеси общую часть в отдельную функцию

2022-01-10 13:45 UTC, wizrdr commented on context/TransactionsContext.js
> +	const handleChangeUserList = user => setUserInputList(user);
Зачем эти 2 функции?

2022-01-10 13:50 UTC, wizrdr commented on helpers/tabBarIconHandler.js
> +const tabBarIconHandler = ({focused}) => (
я бы поменял название, так как эта функция просто возвращает компонент

2022-01-10 13:54 UTC, wizrdr commented on screens/Login.js
> +					onPressButton={() => handelLogIn(email, password)}
без анонимных стрелочных функций

2022-01-10 13:54 UTC, wizrdr commented on screens/Login.js
> +					onPressButton={() => handelSingUp(email, password)}
без анонимных стрелочных функций

2022-01-12 17:02 UTC, merged